language: scala
scala:
- 2.12.2
script:
- sbt clean coverage test coverageReport coverageOff
after_success:
- sbt coveralls
deploy:
  provider: heroku
  api_key:
    secure: wNcujkZfQt2+JX7tl6Qpy5tzMMF3Z5TkLxFhzSpiorE8/febbdT9k4/v5n82weubh2EuIAnvyYHa1LHtRKnRptKmwFgm0JctW55wOb+VNGyvpTpJo1mbEDltzzAq919dHqjtJcdMMvOPcI2RDjBdrKSmu5Ghfyf00JFVbyEaipfAMwehpTlVEc3d96k9QvcRHdVdc+Nmm0sbPDPVhrBfmgUi7WlUbUXct2BKJMsPcpCrXBsAooEOtTQLqXXLlh7C6JwnKmxwvqmuIR/H1e9pjDxPzB/UlZW+AX3Jw45aQ6mtCeZSpR85dtWMdu7R8lq3naCXIsIzMG7gwv8zco+fAUj8K41GuSNL6xp4XXNJ0ZUx2yTZPnxuxhEIAMPXZyeiFfeDSQHAmcG2gtyM7d2NWS0Lmt+eSw7GRaGSiuYyzxW7GixehrtcAdiJx/zFYTbPs6W0JjUpMVjwYq6kzEfRvIMOPUbjD+8wOtQbbAKkT6kyosaEzSrPLRKmQ/TtMcIhPxS2tBWs80bCGstfbE0hqOz6gLvyNOFI45CafEeFvpPlFj9SytODqzNKl9hCTZMHzLCQit0mn/NWjz5Hq953srnEin6ia/Gz6eDpqgJpnexVcCpEy5FHMQduwMTyBrXqS6iUMJZdIYFi8ttbQUuI8LvB7QfWS/MlSc/Xg/cDSTY=
